# Packages
PACKAGES := x11 xcb xcb-randr xcb-icccm xcb-keysyms xcb-event xcb-render freetype2 fontconfig

# Packages only used within tests and not the end build
TEST_PACKAGES := xcb-errors

# Compiler flags
DEBUG_FLAGS := -DDEBUG -g -fsanitize=address -pg
CXX_FLAGS := -Isrc -std=c++17 $(shell pkg-config --cflags $(PACKAGES)) -Wall -Wextra -Wpedantic -Werror -Wno-format-zero-length
RELEASE_FLAGS := -O3

# Libraries
CXX_LIBS := $(shell pkg-config --libs $(PACKAGES))

# Input
SRC := src

# Output
BUILD := build
RELEASE := release

BINARY := /usr/bin/fensterchef
MANUAL_PAGE := /usr/share/man/man1/fensterchef.1.gz

# Find all source files
SOURCES := $(shell find $(SRC) -name '*.cpp' -o -name '*.c')
# Get all corresponding object paths
OBJECTS := $(patsubst $(SRC)/%.cpp,$(BUILD)/%.o,$(patsubst $(SRC)/%.c,$(BUILD)/%.o,$(SOURCES)))

# Find all test sources
TEST_SOURCES := $(shell find tests -name '*.c')
# Get the corresponding output binaries
TESTS := $(patsubst tests/%.c,$(BUILD)/tests/%,$(TEST_SOURCES))
# All objects but the main object
OBJECTS_WITHOUT_MAIN := $(filter-out $(BUILD)/main.o,$(OBJECTS))
# Get the corresponding depency files
TEST_DEPENDENCIES := $(patsubst %,%.d,$(TESTS))

# Get dependencies
DEPENDENCIES := $(patsubst %.o,%.d,$(OBJECTS))

# Sandbox parameters
SANDBOX_DISPLAY := 8
SANDBOX := Xephyr :$(SANDBOX_DISPLAY) +extension RANDR -br -ac -noreset -screen 800x600

.PHONY: default
default: build

# Include dependencies (.d files) generated by g++
-include $(DEPENDENCIES)
# Build each object from corresponding C++ source file
$(BUILD)/%.o: $(SRC)/%.cpp
	mkdir -p $(dir $@)
	g++ $(DEBUG_FLAGS) $(CXX_FLAGS) -c $< -o $@ -MMD

# Build each object from corresponding C source file (for compatibility)
$(BUILD)/%.o: $(SRC)/%.c
	mkdir -p $(dir $@)
	g++ $(DEBUG_FLAGS) $(CXX_FLAGS) -c $< -o $@ -MMD

# Build the main executable from all object files
$(BUILD)/fensterchef: $(OBJECTS)
	mkdir -p $(dir $@)
	g++ $(DEBUG_FLAGS) $(CXX_FLAGS) $(OBJECTS) -o $@ $(CXX_LIBS)

# Tests
.PHONY: tests

# Include dependencies (.d files) generated by gcc
-include $(TEST_DEPENDENCIES)
# Build the test objects
$(BUILD)/tests/%.o: tests/%.c
	mkdir -p $(dir $@)
	g++ $(DEBUG_FLAGS) $(shell pkg-config --cflags $(TEST_PACKAGES)) $(CXX_FLAGS) -c $< -o $@ -MMD

# Build the test executables
$(BUILD)/tests/%: $(BUILD)/tests/%.o $(OBJECTS_WITHOUT_MAIN)
	g++ $(DEBUG_FLAGS) $(CXX_FLAGS) $(OBJECTS_WITHOUT_MAIN) $< -o $@ $(CXX_LIBS) $(shell pkg-config --libs $(TEST_PACKAGES))

tests: $(TESTS)

# Functions
.PHONY: build sandbox stop release install uninstall clean

build: $(BUILD)/fensterchef

sandbox: build
	$(SANDBOX) &
	# wait for x server to start
	sleep 1
	DISPLAY=:$(SANDBOX_DISPLAY) gdb -ex run ./$(BUILD)/fensterchef

stop:
	pkill Xephyr

release:
	mkdir -p $(RELEASE)
	g++ $(RELEASE_FLAGS) $(CXX_FLAGS) $(SOURCES) -o $(RELEASE)/fensterchef $(CXX_LIBS)

$(RELEASE)/fensterchef.1.gz: man/fensterchef.1
	mkdir -p $(RELEASE)
	gzip --best -c man/fensterchef.1 > $@

install: $(RELEASE)/fensterchef.1.gz release
	install $(RELEASE)/fensterchef $(BINARY)
	install $(RELEASE)/fensterchef.1.gz $(MANUAL_PAGE)

uninstall:
	rm $(BINARY)
	rm $(MANUAL_PAGE)

clean:
	rm -rf $(BUILD)
	rm -rf $(RELEASE)
